# Generated by Django 5.1.3 on 2024-11-14 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Backend"),
                            (1, "Frontend"),
                            (2, "Android"),
                            (3, "iOS"),
                        ],
                        verbose_name="Job Type",
                    ),
                ),
                ("job_name", models.CharField(max_length=100, verbose_name="Job Name")),
                (
                    "job_city",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Beijing"),
                            (1, "Shanghai"),
                            (2, "Guangzhou"),
                            (3, "Shenzhen"),
                        ],
                        verbose_name="Job City",
                    ),
                ),
                (
                    "job_responsibility",
                    models.TextField(
                        max_length=1024, verbose_name="Job Responsibility"
                    ),
                ),
                (
                    "job_requirements",
                    models.TextField(max_length=1024, verbose_name="Job Requirements"),
                ),
                ("create_date", models.DateTimeField(verbose_name="Create Date")),
                (
                    "modified_date",
                    models.DateTimeField(verbose_name="Last Modified Date"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
        ),
    ]
